# Generated by Django 5.1.1 on 2024-09-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0002_project_author_project_last_modified_project_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Under Review'), (4, 'COMPLETED')], default=1),
        ),
    ]
