# Generated by Django 5.1.1 on 2024-09-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0003_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Under Review'), (4, 'Completed')], default=1),
        ),
    ]
